export const INPUT_BOX_CLICKED = "INPUT_BOX_CLICKED";
export const INPUT_TEXT_CHANGE = "INPUT_TEXT_CHANGE";
export const UPDATE_ALL_NOTES = "UPDATE_ALL_NOTES";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const MODAL_TOGGLE = "MODAL_TOGGLE";
export const TOGGLE_PINNED_POST = "TOGGLE_PINNED_POST";
export const TOGGLE_COMPLETION = "TOGGLE_COMPLETION";
export const EDIT_NOTE = "EDIT_NOTE";
